# Settings
title: Zapier Platform UI Documentation
description: "Zapier Platform UI"
url: "https://platform.zapier.com" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
baseurl: "" # intentionally left blank, site is served at root
partner_api_invite_url: "https://zapier.typeform.com/to/atnWuF"
partner_count: "5,000+"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Sass Settings
sass:
  sass_dir: assets/stylesheets

# Collections
collections_dir: docs

collections:
  quickstart:
    output: true
    permalink: /:collection/:name
  docs:
    output: true
    permalink: /:collection/:name
  cli_docs:
    output: true
    permalink: /:collection/:name
  cli_tutorials:
    output: true
    permalink: /:collection/:name
  private_integrations:
    output: true
    permalink: /:collection/:name       
  legacy:
    output: true
    permalink: /:collection/:name
  partners:
    output: true
    permalink: /:collection/:name
  partner_success_stories:
    output: true
    permalink: /:collection/:name
  embed:
    output: true
    permalink: /:collection/:name
  conversion:
    output: true
    permalink: /:collection/:name   

defaults:
  - scope:
      path: ""
      type: "quickstart"
    values:
      layout: default
  - scope:
      path: ""
      type: "docs"
    values:
      layout: default
  - scope:
      path: ""
      type: "news"
    values:
      layout: default
  - scope:
      path: ""
      type: "cli_docs"
    values:
      layout: default
  - scope:
      path: ""
      type: "cli_tutorials"
    values:
      layout: default
  - scope:
      path: ""
      type: "legacy"
    values:
      layout: default
  - scope:
      path: ""
      type: "conversion"
    values:
      layout: default
  - scope:
      path: ""
      type: "partners"
    values:
      layout: default
  - scope:
      path: ""
      type: "partner_success_stories"
    values:
      layout: default
  - scope:
      path: ""
      type: "embed"
    values:
      layout: default  
  - scope:
      path: ""
      type: "private_integrations"
    values:
      layout: default

