# Settings
title: Zapier Platform UI Documentation
description: "Zapier Platform UI"
url: "https://platform.zapier.com" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
baseurl: "" # intentionally left blank, site is served at root
partner_api_invite_url: "https://zapier.typeform.com/to/atnWuF"
partner_count: "6,000+"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Sass Settings
sass:
  sass_dir: assets/stylesheets

# Collections
collections_dir: docs

collections:
  quickstart:
    output: true
    permalink: /:collection/:name
  build:
    output: true
    permalink: /:collection/:name
  manage:
    output: true
    permalink: /:collection/:name
  publish:
    output: true
    permalink: /:collection/:name
  embed:
    output: true
    permalink: /:collection/:name    
  reference:
    output: true
    permalink: /:collection/:name
  cli_docs:
    output: true
    permalink: /:collection/:name


defaults:
  - scope:
      path: ""
      type: "quickstart"
    values:
      layout: default
  - scope:
      path: ""
      type: "build"
    values:
      layout: default
  - scope:
      path: ""
      type: "manage"
    values:
      layout: default
  - scope:
      path: ""
      type: "publish"
    values:
      layout: default
  - scope:
      path: ""
      type: "embed"
    values:
      layout: default
  - scope:
      path: ""
      type: "reference"
    values:
      layout: default
  - scope:
      path: ""
      type: "cli_docs"
    values:
      layout: default
